### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by flownex** [majodev/sjgrabber#9]
Hat dieser Tage noch problemlos funktioniert, jetzt kommt jedoch:
TypeError: Cannot call method 'getTime' of null
    at Backbone.Collection.extend.comparator (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\daemon\savedItems.js:1:2280)
    at eval (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\node_modules\underscore\underscore.js:324:28)
    at Array.map (native)
    at Function._.map._.collect (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\node_modules\underscore\underscore.js:98:56)
    at Function._.sortBy (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\node_modules\underscore\underscore.js:320:22)
    at Collection.(anonymous function) [as sortBy] (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\backbone.js:979:23)
    at _.extend.sort (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\backbone.js:841:28)
    at _.extend.set (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\backbone.js:744:22)
    at _.extend.add (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\node_modules\backbone\backbone.js:638:19)
    at loadSavedItems (C:\Users\ADMINI~1\AppData\Local\Temp\2\nw3068_15675\daemon\cacheHandler.js:1:374)

**Comment by majodev** [comment]
Might be linked to the quota exceeded errors. Have you tried to wipe/reset the application?

**Comment by flownex** [comment]
That might be possible, but I have not used it any more, as I moved to SjUpdater.
